### ISSUE TITLE
Not working in Remote-SSH environment.

### ISSUE THREAD

**Issue by zzz00yx** [mtbaqer/vscode-better-folding#5]
I'm using ms-vscode-remote.remote-ssh to connect with my linux server, and install your extension in the remote server. But the extension won't startup directly.

Log output:
```txt
2023-01-29 09:51:16.697 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
2023-01-29 09:51:16.697 [error] Error: Cannot find module './bracketRangesProvider'
```

**Comment by mtbaqer** [comment]
Hey thanks for reporting the problem.

Would you mind clean install [this ](https://open-vsx.org/extension/MohammadBaqer/better-folding)version and let me know if it works?

**Comment by disfated** [comment]
Tried to install v0.2.3 and failed.
1. Manually installing on remote host ends up stuck in infinite loading animation. No useful logs found.
   <video src="https://user-images.githubusercontent.com/430542/215446848-02ca6050-8483-4a6a-93ce-d6faa23f8ce2.mp4"/>
3. If I first install v0.2.3 locally and then from Extension manager click "Install in SSH" it installs old v0.2.2.

**Comment by disfated** [comment]
v0.3.0:
```
2023-02-01 13:21:56.261 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
2023-02-01 13:21:56.261 [error] Error: Cannot find module '/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/node_modules.asar/vscode-textmate'
Require stack:
- /root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js
- /root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/loader.js
- /root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/bootstrap-amd.js
- /root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at Function.Module._load (node:internal/modules/cjs/loader:778:27)
	at Function.r._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
	at Function.v._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
	at Function.w._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at jA.getNodeModule (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:23301)
	at jA.loadTextMate (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:23363)
	at new jA (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:22057)
	at new k2 (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:24180)
	at new f1 (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:24317)
	at new CT (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:327:25876)
	at Object.<anonymous> (/root/.vscode-server/extensions/mohammadbaqer.better-folding-0.3.0/out/main.js:330:8237)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
	at Function.v._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
	at Function.w._load (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/loader.js:5:101)
	at d.pb (/root/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:115:63164)
	at async Promise.all (index 0)
```

**Comment by mtbaqer** [comment]
Just pushed a new update 0.3.1 that fixes the problem for dev containers. Would you mind checking if it fixes this problem as well?

**Comment by disfated** [comment]
Nope, it does not.

**Comment by zzz00yx** [comment]
I tried the 3.0.1 and it loaded successfully. But the folding function was still not working. No arrows that indicate the folding, show at the left of the code. May be confict with other extensions. I'll try later to report more.

**Comment by mtbaqer** [comment]
@zzz00yx any updates?

**Comment by zzz00yx** [comment]
Nope, both 0.3.1 and 0.4.0 not work in a tidy server with no other extensions.

I find the arrows show ~0.5s after I reload the vscode window.
In this ~0.5s, I click the arrow and the default vscode-style folding function works.

And then the arrows disappear, no folding any more.
