### ISSUE TITLE
Extension broken after VSCode latest update 1.94.0

### ISSUE THREAD

**Issue by Kevsnz** [mtbaqer/vscode-better-folding#66]
**Describe the bug**
Extension fails to load.

**To Reproduce**
1. Update VS Code to latest version (1.94.0+)
2. Install this extension
3. Try to fold any part of the code (doesn't work)
4. Open Output pane, Extension Host source. There will be an error.

**Expected behavior**
Extension functionality should be available.

**Desktop:**
 - OS: Win 10
 - VS Code version: 1.94.0

**Error text**
```
2024-10-05 12:48:25.163 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
2024-10-05 12:48:25.163 [error] Error: Cannot find module '...VS Code\resources\app\node_modules.asar\vscode-textmate'
Require stack:
- ...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js
- ...VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js
	at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
	at i._resolveFilename (node:electron/js2c/utility_init:2:13739)
	at t._resolveFilename (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22704)
	at Module._load (node:internal/modules/cjs/loader:993:27)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at HA.getNodeModule (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:59969)
	at HA.loadTextMate (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:60031)
	at new HA (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:58625)
	at new O2 (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:60848)
	at new v1 (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:60985)
	at new IT (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:327:62852)
	at Object.<anonymous> (...\.vscode\extensions\mohammadbaqer.better-folding-0.5.1\out\main.js:330:3062)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///...VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at async Promise.all (index 0)
```

**Comment by han013** [comment]
Yes, I have the same problem. This will cause a large number of crash logs to be written, filling up my disk.

**Comment by almaceleste** [comment]
the same problem on Linux

- OS: Ubuntu Studio 24.10
- VS Code: 1.95.3

**Comment by CrayonSSR** [comment]
Same, install `Better Folding`, restart vscode, try fold some code, then nothing happend...

- Win10 2024.12
- Vscode 1.96.2
- Better Folding 0.5.1 (Last Updated 2024-12-28, 22:41:22)
